// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NR155910155992.MemoGame.Dao;

#nullable disable

namespace NR155910155992.MemoGame.Dao.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20251122225613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "images/card1.png",
                            Name = "Card 1"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "images/card2.png",
                            Name = "Card 2"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "images/card3.png",
                            Name = "Card 3"
                        });
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 0, 1, 30, 0),
                            GameDate = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GameMode = 0,
                            GameType = 1
                        });
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.PlayerGameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardsUncovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("PlayerGameResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardsUncovered = 12,
                            GameSessionId = 1,
                            IsWinner = true,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Player1"
                        });
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.PlayerGameResult", b =>
                {
                    b.HasOne("NR155910155992.MemoGame.Dao.Models.GameSession", "GameSession")
                        .WithMany("PlayerResults")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NR155910155992.MemoGame.Dao.Models.UserProfile", "User")
                        .WithMany("PlayerResults")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.GameSession", b =>
                {
                    b.Navigation("PlayerResults");
                });

            modelBuilder.Entity("NR155910155992.MemoGame.Dao.Models.UserProfile", b =>
                {
                    b.Navigation("PlayerResults");
                });
#pragma warning restore 612, 618
        }
    }
}
